#version 430 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

uniform int u_TileCount;
uniform int u_TileMax;

layout(std430, binding = 1) buffer B_TileIndex
{
    uvec2 g_TileIndex[];
};

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i >= uint(max(u_TileCount, 0)))
        return;

    uint c = g_TileIndex[i].y;
    if (c > uint(max(u_TileMax, 0)))
        g_TileIndex[i].y = uint(max(u_TileMax, 0));
}
